import json
import logging
import re
from typing import List, Dict, Any, Optional

logger = logging.getLogger(__name__)

class SpecTranslator:
    """
    OMNIWEB — BLOQUE: OMNI_CATALYST_SPEC_TRANSLATOR_V0.3.
    Translator for high-level intent into Omni MissionSteps contract.
    """
    
    def __init__(self):
        self.required_fields = ["objective", "rationale", "steps"]
        # Pattern to detect steps that imply direct uncontrolled execution or bypass
        self.suspect_patterns = [
            r"DIRECT_WRITE", r"BYPASS_GOVERNANCE", r"AUTO_COMMIT", 
            r"SILENT_EXECUTION", r"MASTER_AUTHORITY"
        ]

    def validate_spec_contract(self, raw_json: str) -> Optional[Dict[str, Any]]:
        """
        Validates the MissionSteps contract from catalyst output.
        """
        try:
            data = json.loads(raw_json)
            # Ensure required fields
            for field in self.required_fields:
                if field not in data:
                    logger.warning(f"Spec Translator: Missing field {field}")
                    return None
            
            # Ensure steps format
            if not isinstance(data["steps"], list) or len(data["steps"]) == 0:
                logger.warning("Spec Translator: Invalid or empty steps list")
                return None
            
            # Ensure each step is safe (advisory only)
            for step in data["steps"]:
                if "step" not in step:
                    return None
                if not self._is_step_safe(step["step"]):
                    logger.warning(f"Spec Translator: Blocked unsafe step: {step['step']}")
                    return None
                    
            return data
            
        except Exception as e:
            logger.error(f"Spec Translator contract violation: {e}")
            return None

    def _is_step_safe(self, step_text: str) -> bool:
        """
        Heuristic check for language that implies bypass or authority.
        """
        content = step_text.upper()
        for p in self.suspect_patterns:
            if re.search(p, content):
                return False
        # Ensure it doesn't sound like a "COMMAND" to the OS
        if step_text.strip().startswith(("rm ", "del ", "format ")):
            return False
            
        return True

    def normalize_spec(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Ensures final format is ready for DraftEngine.
        Adds mandatory 'PENDING' status for all catalyst steps.
        """
        for step in data.get("steps", []):
            step["status"] = "PENDING"
            if "reason" not in step:
                step["reason"] = "Generated by Spec Translator Catalyst (V0.3)"
                
        return data

spec_translator = SpecTranslator()
