class CreatorEditor {
    constructor() {
        this.currentPath = null;
        this.originalContent = null;
        this.roots = ["chips", "backend", "frontend", "docs"];
        this.currentRoot = "chips";
    }

    async init() {
        console.log("Initializing Creator Editor...");
        this.renderLayout();
        await this.loadTree();
    }

    renderLayout() {
        const panel = document.getElementById('cockpit-main-panel');
        if (!panel) return;

        panel.innerHTML = `
            <div class="editor-container">
                <div class="editor-sidebar">
                    <div class="sidebar-header">
                        <h3>File Tree</h3>
                        <select id="editor-root-selector" onchange="window.creatorEditor.switchRoot(this.value)" style="background: transparent; border: none; color: #888; font-size: 0.7rem; outline: none;">
                            ${this.roots.map(r => `<option value="${r}">${r.toUpperCase()}</option>`).join('')}
                        </select>
                    </div>
                    <div class="file-tree" id="file-tree-root">
                        <div class="loading-indicator">Scanning files...</div>
                    </div>
                </div>
                
                <div class="editor-main">
                    <div id="editor-change-banner" class="change-banner" style="display: none; background: rgba(212, 175, 55, 0.1); border-bottom: 1px solid var(--creator-gold); padding: 5px 15px; font-size: 0.75rem; align-items: center; justify-content: space-between;">
                        <span><i class="ai-orb-tiny" style="width: 10px; height: 10px; display: inline-block; margin-right: 5px;"></i> Propuesta técnica del Swarm disponible para este archivo</span>
                        <div style="display: flex; gap: 10px;">
                            <button class="btn-mini-action" onclick="window.creatorEditor.toggleDiffView()">Ver Cambios</button>
                            <button class="btn-mini-action primary" onclick="window.creatorEditor.approveProposal()">Aprobar</button>
                        </div>
                    </div>
                    <div class="editor-header">
                        <div class="current-file-path" id="editor-file-path">No file selected</div>
                        <div class="editor-actions">
                            <button class="btn-propose" id="editor-btn-propose" onclick="window.creatorEditor.proposeEdit()" disabled>Propose Changes</button>
                        </div>
                    </div>
                    <div class="editor-body">
                        <textarea id="code-textarea" spellcheck="false" placeholder="Select a file to start editing..." oninput="window.creatorEditor.handleInput()"></textarea>
                        <div id="editor-diff-view" class="diff-overlay" style="display: none; position: absolute; top: 0; left: 0; width: 100%; height: 100%; background: #0a0a0f; overflow-y: auto; z-index: 100; font-family: monospace; padding: 20px; box-sizing: border-box;">
                             <!-- Diff content generated by script -->
                        </div>
                    </div>
                </div>

                <div class="editor-assist">
                    <div class="assist-header">
                        <div class="ai-orb-tiny" style="width: 15px; height: 15px;"></div>
                        <h3>Copilot Assist</h3>
                    </div>
                    <div class="assist-content" id="editor-assist-content">
                        <p style="opacity: 0.5;">Select code or a file to get assistance.</p>
                    </div>
                    <div class="assist-controls">
                        <button class="assist-btn" onclick="window.creatorEditor.requestAssist('explain')">💡 Explain this file</button>
                        <button class="assist-btn" onclick="window.creatorEditor.requestAssist('optimize')">⚡ Optimize functions</button>
                        <button class="assist-btn" onclick="window.creatorEditor.requestAssist('refactor')">🔨 Refactor code</button>
                    </div>
                </div>
            </div>
        `;
    }

    async switchRoot(newRoot) {
        this.currentRoot = newRoot;
        await this.loadTree();
    }

    async loadTree() {
        const treeRoot = document.getElementById('file-tree-root');
        if (!treeRoot) return;

        try {
            const res = await fetch(`/api/v1/editor/files?root=${this.currentRoot}`, {
                headers: { 'Authorization': 'Bearer omniweb-dev-secret-token' }
            });
            const data = await res.json();
            this.renderTree(data, treeRoot);
        } catch (err) {
            treeRoot.innerHTML = `<div class="error-msg">Failed to load tree</div>`;
        }
    }

    renderTree(nodes, container) {
        container.innerHTML = nodes.map(node => this.createNodeHtml(node)).join('');
    }

    createNodeHtml(node) {
        const icon = node.is_dir ? '📁' : '📄';
        const childrenHtml = node.children && node.children.length > 0
            ? `<div class="tree-children" id="children-${node.path.replace(/[^a-zA-Z0-9]/g, '-')}" style="display: none;">
                ${node.children.map(c => this.createNodeHtml(c)).join('')}
               </div>`
            : '';

        return `
            <div class="tree-node-wrapper">
                <div class="tree-node" onclick="window.creatorEditor.handleNodeClick('${node.path}', ${node.is_dir})">
                    <i>${icon}</i>
                    <span>${node.name}</span>
                </div>
                ${childrenHtml}
            </div>
        `;
    }

    handleNodeClick(path, isDir) {
        if (isDir) {
            const childrenId = `children-${path.replace(/[^a-zA-Z0-9]/g, '-')}`;
            const el = document.getElementById(childrenId);
            if (el) el.style.display = el.style.display === 'none' ? 'block' : 'none';
        } else {
            this.loadFile(path);
        }
    }

    async loadFile(path) {
        const textarea = document.getElementById('code-textarea');
        const pathDisplay = document.getElementById('editor-file-path');
        const proposeBtn = document.getElementById('editor-btn-propose');

        // Helper to update path display (handles DIV or INPUT)
        const updatePathDisplay = (text) => {
            if (!pathDisplay) return;
            if (pathDisplay.nodeName === 'INPUT') pathDisplay.value = text;
            else pathDisplay.innerText = text;
        };

        try {
            updatePathDisplay("Loading...");
            const res = await fetch(`/api/v1/editor/file/read?path=${encodeURIComponent(path)}`, {
                headers: {
                    'Authorization': 'Bearer omniweb-dev-secret-token',
                    'X-Shell-Identity': 'omniweb-shell'
                }
            });
            const data = await res.json();

            if (!res.ok) {
                const errMsg = data.detail || data.error || `HTTP ${res.status}`;
                updatePathDisplay(`Error: ${errMsg}`);
                console.error("Editor Load Error:", errMsg);
                return { error: errMsg };
            }

            this.currentPath = path;
            this.originalContent = data.content;

            // Sync legacy UI if it exists
            if (textarea) textarea.value = data.content;
            updatePathDisplay(data.path);
            if (proposeBtn) proposeBtn.disabled = true;

            // Highlight active node in tree
            document.querySelectorAll('.tree-node').forEach(n => n.classList.remove('active'));
            const nodes = document.querySelectorAll('.tree-node');
            nodes.forEach(n => {
                if (n.innerText.includes(path.split(path.includes('/') ? '/' : '\\').pop())) {
                    n.classList.add('active');
                }
            });

            return data.content;
        } catch (err) {
            console.error("FS_READ Fail:", err);
            const errMsg = err.message || "Network Error";
            return { error: errMsg };
        }
    }

    updateFromState(state) {
        if (!state || !this.currentPath) return;

        // Check for matching proposals
        const activeProposal = (state.proposals || []).find(p =>
            p.target_file === this.currentPath ||
            this.currentPath.endsWith(p.target_file)
        );

        const banner = document.getElementById('editor-change-banner');
        if (activeProposal) {
            this.activeProposal = activeProposal;
            if (banner) banner.style.display = 'flex';
        } else {
            this.activeProposal = null;
            if (banner) banner.style.display = 'none';
            this.toggleDiffView(false); // Hide diff if no active proposal
        }
    }

    toggleDiffView(force) {
        const diffView = document.getElementById('editor-diff-view');
        const textarea = document.getElementById('code-textarea');
        if (!diffView) return;

        const show = (force !== undefined) ? force : diffView.style.display === 'none';

        if (show && this.activeProposal) {
            diffView.style.display = 'block';
            textarea.style.display = 'none';
            this.renderDiffContent(this.activeProposal);
        } else {
            diffView.style.display = 'none';
            textarea.style.display = 'block';
        }
    }

    renderDiffContent(proposal) {
        const diffView = document.getElementById('editor-diff-view');
        if (!diffView) return;

        const escape = (unsafe) => unsafe.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
        const diffText = proposal.diff_preview || "No preview available.";
        const lines = diffText.split('\n');

        const htmlLines = lines.map(line => {
            let cls = "";
            if (line.startsWith('-')) cls = "removed";
            else if (line.startsWith('+')) cls = "added";
            else if (line.startsWith('@@')) cls = "info";

            return `<div class="diff-line ${cls}" style="white-space: pre-wrap; margin-bottom: 2px; padding: 0 5px; border-radius: 2px; ${cls === 'removed' ? 'background: rgba(255, 0, 0, 0.1); color: #ff5555;' : cls === 'added' ? 'background: rgba(0, 255, 0, 0.1); color: #55ff55;' : ''}">${escape(line)}</div>`;
        }).join('');

        diffView.innerHTML = `
            <div style="display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid rgba(255,255,255,0.1); padding-bottom: 10px; margin-bottom: 15px;">
                <h4 style="margin: 0; color: var(--creator-gold);">MODO PREVIEW: CAMBIO SUGERIDO</h4>
                <button class="btn-mini-action" onclick="window.creatorEditor.toggleDiffView(false)">Cerrar Preview</button>
            </div>
            <div style="font-size: 0.8rem; line-height: 1.4;">${htmlLines}</div>
        `;
    }

    async approveProposal() {
        if (!this.activeProposal || !window.builderUI) return;
        if (confirm("¿Confirmas la aplicación técnica de este parche?")) {
            await window.builderUI.decidePreview(true);
        }
    }

    handleInput() {
        const textarea = document.getElementById('code-textarea');
        const proposeBtn = document.getElementById('editor-btn-propose');

        if (textarea.value !== this.originalContent) {
            proposeBtn.disabled = false;
        } else {
            proposeBtn.disabled = true;
        }
    }

    async proposeEdit() {
        const textarea = document.getElementById('code-textarea');
        const proposeBtn = document.getElementById('editor-btn-propose');

        if (!this.currentPath) return;

        proposeBtn.innerText = "Generating Preview...";
        proposeBtn.disabled = true;

        try {
            const res = await fetch('/api/v1/editor/file/propose-edit', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': 'Bearer omniweb-dev-secret-token'
                },
                body: JSON.stringify({
                    path: this.currentPath,
                    content: textarea.value
                })
            });
            const data = await res.json();

            if (data.preview_id) {
                // Open the preview system
                if (window.builderUI) {
                    window.builderUI.showPreview(data.preview_id);
                } else {
                    alert("Patch generated. ID: " + data.preview_id);
                }
            }
        } catch (err) {
            alert("Failed to propose edit");
        } finally {
            proposeBtn.innerText = "Propose Changes";
            this.handleInput();
        }
    }

    async requestAssist(action) {
        const textarea = document.getElementById('code-textarea');
        const assistContent = document.getElementById('editor-assist-content');
        const selection = textarea.value.substring(textarea.selectionStart, textarea.selectionEnd);

        if (!this.currentPath && !selection) {
            assistContent.innerHTML = `<p style='color: #f1c40f;'>Please select a file or code snippet first.</p>`;
            return;
        }

        assistContent.innerHTML = `<div class="loading-indicator">Consulting Copilot...</div>`;

        try {
            const res = await fetch('/api/v1/editor/copilot/assist', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': 'Bearer omniweb-dev-secret-token'
                },
                body: JSON.stringify({
                    action: action,
                    path: this.currentPath || "unknown",
                    code: selection || null
                })
            });
            const data = await res.json();

            assistContent.innerHTML = `
                <div class="assist-response">
                    ${this.formatMarkdown(data.response)}
                </div>
            `;
        } catch (err) {
            assistContent.innerHTML = `<p class='error'>Failed to get assistance.</p>`;
        }
    }

    formatMarkdown(text) {
        // Simple markdown formatter
        return text
            .replace(/```([\s\S]*?)```/g, '<pre><code>$1</code></pre>')
            .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
            .replace(/\*(.*?)\*/g, '<em>$1</em>')
            .replace(/\n/g, '<br/>');
    }

    // --- WORKSPACE BRIDGE ---
    async openFile(path, callback) {
        const content = await this.loadFile(path);
        if (content !== null && callback) callback(content);
        return content;
    }

    async saveFile(path, content, callback) {
        try {
            const res = await fetch('/api/v1/creator/fs/write', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': 'Bearer omniweb-dev-secret-token',
                    'X-Shell-Identity': 'omniweb-shell'
                },
                body: JSON.stringify({ path: path, content: content })
            });
            const data = await res.json();
            if (data.status === 'success') {
                this.originalContent = content;
                if (callback) callback(true, data);
            } else {
                alert("Save error: " + (data.detail || "Unknown error"));
                if (callback) callback(false, data);
            }
        } catch (err) {
            alert("Connection error during save");
            if (callback) callback(false, err);
        }
    }
}

window.creatorEditor = new CreatorEditor();
